#ifndef Constants_h
#define Constants_h


#define QUIT true


/* GAME OBJECTS CONSTANTS */

// global game objects
#define GRAVITY 							120.0f
#define MAX_VELOCITY_X 						50.0f
#define MAX_VELOCITY_Y 						100.0f
#define IS_ALIVE 							true
#define IS_DEAD 							false
#define COLLIDER_INITIAL_ACCELERATION_X 	0.0f
#define COLLIDER_INITIAL_ACCELERATION_Y 	0.0f
#define COLLIDER_INITIAL_MASS 				10.0f
#define COLLIDER_INITIAL_ELASTIC 			1.0f
#define COLLIDER_INITIAL_POSITION_X 		0.0f
#define COLLIDER_INITIAL_POSITION_Y 		0.0f
#define COLLIDER_INITIAL_VELOCITY_X 		0.0f
#define COLLIDER_INITIAL_VELOCITY_Y 		0.0f
//#define MAP_WIDTH                            2000
//#define MAP_HEIGHT                            2000

// Collisions
#define COLLISION_TYPE_NONE					0

#define COLLISION_TYPE_HERO_MINION			1
#define COLLISION_TYPE_HERO_BASIC		    2
#define COLLISION_TYPE_HERO_SURFACE         3
#define COLLISION_TYPE_HERO_SPECIAL         4
#define COLLISION_TYPE_HERO_POWERUP			11

#define COLLISION_TYPE_MINION_MINION		13
#define COLLISION_TYPE_MINION_BASIC		    7
#define COLLISION_TYPE_MINION_SURFACE       8
#define COLLISION_TYPE_MINION_SPECIAL       9

#define COLLISION_TYPE_POWERUP_SURFACE		12
#define COLLISION_TYPE_POWERUP_SPECIAL      14
#define COLLISION_TYPE_POWERUP_BASIC        16

#define COLLISION_TYPE_BULLET_HERO         	17
#define COLLISION_TYPE_BULLET_SURFACE       18
#define COLLISION_TYPE_BULLET_SPECIAL       19
#define COLLISION_TYPE_BULLET_MINION		20

#define COLLISION_TYPE_HERO_COLLECTIBLE		21


// hero initial
#define HERO_INITIAL_POSITION_X 		    76.0f
#define HERO_INITIAL_POSITION_Y 			200.0f
#define HERO_INITIAL_VELOCITY_X 			5.0f
#define HERO_INITIAL_VELOCITY_Y 			0.0f
#define HERO_JUMP_UP_SPEED 					150.0f
#define HERO_WIDTH_INITIAL					45.0f
#define HERO_HEIGHT_INITIAL					45.0f
#define HERO_BOUNDING_BOX_X 				45.0f
#define HERO_BOUNDING_BOX_Y 				45.0f
#define HERO_MASS 							5.0f
#define HERO_ANIMATION_MAX_FRAME_NUM 		8
#define HERO_FRAME_HEIGHT 					80
#define HERO_FRAME_WIDTH 					75

#define HERO_POSE_COUNT						9

#define HERO_POSE_FIRE						10
#define HERO_POSE_FALL_LEFT					9
#define HERO_POSE_FALL_RIGHT				8
#define HERO_POSE_JUMP_LEFT					5
#define HERO_POSE_JUMP_RIGHT				4
#define HERO_POSE_MOVE_LEFT					3
#define HERO_POSE_MOVE_RIGHT				2
#define HERO_POSE_STAND_LEFT				1
#define HERO_POSE_STAND_RIGHT				0

#define HERO_COLLISION_INVALID_TIME			3000

#define HERO_POS_MOVE_FACTOR				0.05	



// minion initial
#define MINION_INITIAL_WIDTH 				45.0f
#define MINION_INITIAL_HEIGHT 				45.0f
#define MINION_INITIAL_VELOCITY_X 			5.0f
#define MINION_INITIAL_VELOCITY_Y 			0.0f
#define MINION_BOUNDING_BOX_X 				45.0f
#define MINION_BOUNDING_BOX_Y 				45.0f
#define MINION_MASS 						15.0f
#define MINION_LEVEL_ONE_NUM 				48
#define MINION_LEVEL_TWO_NUM 				48
#define MINION_LEVEL_THREE_NUM 				48
#define MINION_FRAME_WIDTH					60
#define MINION_FRAME_HEIGHT					60
#define MINION_ANIMATION_MAX_FRAME_NUM		6
#define MINION_POSE_COUNT					10
#define MINION_POSE_MOVE_RIGHT				0
#define MINION_POSE_MOVE_LEFT				1
#define MINION_POSE_JUMP_LEFT				2
#define MINION_POSE_JUMP_RIGHT				3
#define MINION_POSE_CRUNCH_LEFT				4
#define MINION_POSE_CRUNCH_RIGHT			5
#define MINION_POSE_STAND_LEFT				6
#define MINION_POSE_STAND_RIGHT				7
#define MINION_POSE_FALL_LEFT				8
#define MINION_POSE_FALL_RIGHT				9

#define MINION_COLLISION_STOP_TIME			3000
#define MINION_POS_MOVE_FACTOR				0.1	

// powerup initial
#define POWERUP_VALID_TIME					5000
#define POWERUP_DIM_TIME					200
#define POWERUP_INITIAL_WIDTH				45.0f
#define POWERUP_INITIAL_HEIGHT				45.0f
#define POWERUP_BOUNDING_BOX_X 				45.0f
#define POWERUP_BOUNDING_BOX_Y 				45.0f
#define POWERUP_MASS 						15.0F
#define POWERUP_CODE_COUNT					3
#define POWERUP_CODE_NONE					0
#define POWERUP_CODE_SPEED_UP				1
#define POWERUP_SPEED_UP_MAX_SPEED          80.0f
#define POWERUP_CODE_FLOAT					2
#define POWERUP_FLOAT_GRAVITY		        30.0f
#define POWERUP_CODE_FIRE					3
#define POWERUP_ANIMATION_MAX_FRAME_NUM		5
#define POWERUP_FRAME_WIDTH					30
#define POWERUP_FRAME_HEIGHT				25
#define POWERUP_POSE_BLING					0
#define POWERUP_POSE_DIM					1

// bullet initial
#define BULLET_INITIAL_WIDTH				25.0f
#define BULLET_INITIAL_HEIGHT				25.0f
#define BULLET_INITIAL_VELOCITY_X			5.0f
#define BULLET_INITIAL_VELOCITY_Y			0.0f
#define BULLET_MASS							15.0f
#define BULLET_BOUNDING_BOX_X				25.0f
#define BULLET_BOUNDING_BOX_Y				25.0f
#define BULLET_FRAME_WIDTH					13
#define BULLET_FRAME_HEIGHT					13
#define BULLET_ANIMATION_MAX_FRAME_NUM		6
#define BULLET_POSE_COUNT					2
#define BULLET_POSE_FLY_LEFT				1
#define BULLET_POSE_FLY_RIGHT				0

// tile initial
#define TILE_INITIAL_WIDTH					45.0f
#define TILE_INITIAL_HEIGHT					45.0f
#define TILE_TYPE_BASIC						1
#define TILE_TYPE_SURFACE					2
#define TILE_TYPE_SPECIAL                   3

// collectible
#define COLLECTIBLE_INITIAL_WIDTH				25.0f
#define COLLECTIBLE_INITIAL_HEIGHT				25.0f
#define COLLECTIBLE_INITIAL_VELOCITY_X			5.0f
#define COLLECTIBLE_INITIAL_VELOCITY_Y			0.0f
#define COLLECTIBLE_MASS						15.0f
#define COLLECTIBLE_BOUNDING_BOX_X				25.0f
#define COLLECTIBLE_BOUNDING_BOX_Y				25.0f
#define COLLECTIBLE_FRAME_WIDTH					13
#define COLLECTIBLE_FRAME_HEIGHT				13
#define COLLECTIBLE_ANIMATION_MAX_FRAME_NUM		6
#define COLLECTIBLE_POSE_COUNT					2
#define COLLECTIBLE_POSE_LIVE					0
#define COLLECTIBLE_POSE_DEAD					1
#define COLLECTIBLE_DEAD_TIME					500
#define SCORE_INREMENT                          10

// map initial
#define MAP_TYPE_NONE                       1
#define MAP_TYPE_NORMAL                     2
#define MAP_TYPE_SEA                        3
#define MAP_TYPE_SNOW                       4
#define MAP_WIDTH                           3600.0
#define MAP_HEIGHT                          450.0F

// camera initial
#define CAMERA_MODE_CENTER					1
#define CAMERA_MODE_TOP_LEFT				2
#define CAMERA_OFFSET_FROM_HERO_X			100
#define CAMERA_OFFSET_FROM_HERO_Y			100



// game info initial

#define LOSE_TEXTURE_POSITION_X 			640.0f
#define LOSE_TEXTURE_POSITION_Y 			360.0f
#define WIN_TEXTURE_POSITION_X 				640.0f
#define WIN_TEXTURE_POSITION_Y 				360.0f
#define INIT_LEVEL 							1
#define INIT_LIFE 							3


// game control
#define CONTROL_WASD						0
#define CONTROL_IJKL						1
#define CONTROL_ARROWKEYS					2




/* GAME SETTING CONSTANTS*/

// language setting
#define CURRENT_LANGUAGE 1
#define LANGUAGE_ENGLISH 1
#define LANGUAGE_CHINESE 2

// menu setting


//**********BUTTON ARRTRIBUTES************//
#define BUTTON_WIDTH 190.0f
#define BUTTON_HEIGHT 49.0f
//**********BUTTON ARRTRIBUTES************//

//**********MAIN_MENU SETTING***********************//
#define MAIN_MENU_LABEL_SPACE WINDOW_HEIGHT/6
#define MAIN_MENU_START_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define MAIN_MENU_START_BUTTON_POSITION_Y MAIN_MENU_TEXTURE_POSITION_Y+MAIN_MENU_LABEL_SPACE-BUTTON_HEIGHT/2
#define MAIN_MENU_LANGUAGE_SETTING_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define MAIN_MENU_LANGUAGE_SETTING_BUTTON_POSITION_Y MAIN_MENU_START_BUTTON_POSITION_Y+MAIN_MENU_LABEL_SPACE

#define MAIN_MENU_INSTRUCTION_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define MAIN_MENU_INSTRUCTION_BUTTON_POSITION_Y MAIN_MENU_LANGUAGE_SETTING_BUTTON_POSITION_Y+MAIN_MENU_LABEL_SPACE

#define MAIN_MENU_QUIT_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define MAIN_MENU_QUIT_BUTTON_POSITION_Y MAIN_MENU_INSTRUCTION_BUTTON_POSITION_Y+MAIN_MENU_LABEL_SPACE

#define MAIN_MENU_TEXTURE_POSITION_X WINDOW_WIDTH/2
#define MAIN_MENU_TEXTURE_POSITION_Y WINDOW_HEIGHT/8
//**********MAIN_MENU SETTING***********************//



//**********SETTING_MENU SETTING********************//
#define SETTING_MENU_TEXTURE_POSITION_X WINDOW_WIDTH/2
#define SETTING_MENU_TEXTURE_POSITION_Y WINDOW_HEIGHT/8

#define SETTING_MENU_LABEL_SPACE WINDOW_HEIGHT/6
#define SETTING_MENU_FIRST_LANGUAGE_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define SETTING_MENU_FIRST_LANGUAGE_BUTTON_POSITION_Y SETTING_MENU_TEXTURE_POSITION_Y+SETTING_MENU_LABEL_SPACE-BUTTON_HEIGHT/2
#define SETTING_MENU_SECOND_LANGUAGE_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define SETTING_MENU_SECOND_LANGUAGE_BUTTON_POSITION_Y SETTING_MENU_FIRST_LANGUAGE_BUTTON_POSITION_Y+SETTING_MENU_LABEL_SPACE
#define SETTING_MENU_RETURN_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define SETTING_MENU_RETURN_BUTTON_POSITION_Y SETTING_MENU_SECOND_LANGUAGE_BUTTON_POSITION_Y+SETTING_MENU_LABEL_SPACE
//**********SETTING_MENU SETTING********************//

//**********INSTRUCTION MENU SETTING****************//
#define INSTRUCTION_MENU_LABEL_SPACE WINDOW_HEIGHT/6

#define INSTRUCTION_MENU_TEXTURE_POSITION_X WINDOW_WIDTH/2
#define INSTRUCTION_MENU_TEXTURE_POSITION_Y WINDOW_HEIGHT/8
#define INSTRUCTION_MENU_RETURN_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define INSTRUCTION_MENU_RETURN_BUTTON_POSITION_Y INSTRUCTION_MENU_TEXTURE_POSITION_Y+5*INSTRUCTION_MENU_LABEL_SPACE-BUTTON_HEIGHT/2

//**********INSTRUCTION MENU SETTING****************//

//**********PAUSE MENU SETTING**********************//
#define PAUSE_MENU_LABEL_SPACE WINDOW_HEIGHT/6
#define PAUSE_MENU_TEXTURE_POSITION_X WINDOW_WIDTH/2
#define PAUSE_MENU_TEXTURE_POSITION_Y WINDOW_HEIGHT/8

#define PAUSE_MENU_SETTING_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define PAUSE_MENU_SETTING_BUTTON_POSITION_Y PAUSE_MENU_TEXTURE_POSITION_Y+2*PAUSE_MENU_LABEL_SPACE-BUTTON_HEIGHT/2
#define PAUSE_MENU_INSTRUCTION_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define PAUSE_MENU_INSTRUCTION_BUTTON_POSITION_Y PAUSE_MENU_SETTING_BUTTON_POSITION_Y+PAUSE_MENU_LABEL_SPACE
#define PAUSE_MENU_RETURN_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define PAUSE_MENU_RETURN_BUTTON_POSITION_Y PAUSE_MENU_INSTRUCTION_BUTTON_POSITION_Y+PAUSE_MENU_LABEL_SPACE
//**********PAUSE MENU SETTING**********************//

//**********PASS MENU SETTING***********************//
#define PASS_MENU_TEXTURE_POSITION_X WINDOW_WIDTH/2
#define PASS_MENU_TEXTURE_POSITION_Y WINDOW_HEIGHT/8
#define PASS_MENU_LABEL_SPACE WINDOW_HEIGHT/6

#define PASS_MENU_NEXT_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define PASS_MENU_NEXT_BUTTON_POSITION_Y PASS_MENU_TEXTURE_POSITION_Y+PASS_MENU_LABEL_SPACE-BUTTON_HEIGHT/2

//**********PASS MENU SETTING***********************//

//**********LOSE MENU SETTING***********************//
#define LOSE_MENU_TEXTURE_POSITION_X WINDOW_WIDTH/2
#define LOSE_MENU_TEXTURE_POSITION_Y WINDOW_HEIGHT/8
#define LOSE_MENU_LABEL_SPACE WINDOW_HEIGHT/6

#define LOSE_MENU_RESTART_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define LOSE_MENU_RESTART_BUTTON_POSITION_Y LOSE_MENU_TEXTURE_POSITION_Y+LOSE_MENU_LABEL_SPACE-BUTTON_HEIGHT/2
#define LOSE_MENU_RETURN_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define LOSE_MENU_RETURN_BUTTON_POSITION_Y LOSE_MENU_RESTART_BUTTON_POSITION_Y+LOSE_MENU_LABEL_SPACE
//**********LOSE MENU SETTING***********************//

//**********WIN MENU SETTING************************//
#define WIN_MENU_TEXTURE_POSITION_X WINDOW_WIDTH/2
#define WIN_MENU_TEXTURE_POSITION_Y WINDOW_HEIGHT/8
#define WIN_MENU_LABEL_SPACE WINDOW_HEIGHT/6

#define WIN_MENU_RETURN_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define WIN_MENU_RETURN_BUTTON_POSITION_Y WIN_MENU_TEXTURE_POSITION_Y+WIN_MENU_LABEL_SPACE-BUTTON_HEIGHT/2
#define WIN_MENU_QUIT_BUTTON_POSITION_X WINDOW_WIDTH/2-BUTTON_WIDTH/2
#define WIN_MENU_QUIT_BUTTON_POSITION_Y WIN_MENU_RETURN_BUTTON_POSITION_Y+WIN_MENU_LABEL_SPACE
//**********WIN MENU SETTING************************//

//**********POWER UP ICON SETTING*******************//
#define POWERUP_ICON_WIDTH 104.0f
#define POWERUP_ICON_HEIGHT 104.0f
#define POWERUP_ICON_TEXTURE_POSITION_X WINDOW_WIDTH/6
#define POWERUP_ICON_TEXTURE_POSITION_Y WINDOW_HEIGHT/12-40.0f

#define POWERUP_ICON_FLOAT_POSITION_X 312.0f
#define POWERUP_ICON_FLOAT_POSITION_Y 104.0f
#define POWERUP_ICON_SPEED_UP_POSITION_X 0.0f
#define POWERUP_ICON_SPEED_UP_POSITION_Y 208.0f
#define POWERUP_ICON_FIRE_POSITION_X 312.0f
#define POWERUP_ICON_FIRE_POSITION_Y 0.0f

#define POWERUP_ICON_TEXTURE_WIDTH 90.0f
#define POWERUP_ICON_TEXTURE_HEIGHT 90.0f
//**********POWER UP ICON SETTING*******************//

//**********INFO SETTING***************************//
#define LIFE_TEXTURE_POSITION_X 			WINDOW_WIDTH/2 - 120.0f
#define LIFE_TEXTURE_POSITION_Y 			WINDOW_HEIGHT/12

#define LEVEL_TEXTURE_POSITION_X 			WINDOW_WIDTH - 360.0f
#define LEVEL_TEXTURE_POSITION_Y 			WINDOW_HEIGHT/12

#define STATE_TEXTURE_POSITION_X            POWERUP_ICON_TEXTURE_POSITION_X - 100.0f
#define STATE_TEXTURE_POSITION_Y            WINDOW_HEIGHT/12

#define SCORE_TEXTURE_POSITION_X 			WINDOW_WIDTH - 220.0f
#define SCORE_TEXTURE_POSITION_Y 			WINDOW_HEIGHT/12
//**********INFO SETTING***************************//

//**********CHECK POINT SETTING*******************//
#define CHECK_POINT_TEXTURE_WIDTH 45.0f
#define CHECK_POINT_TEXTURE_HEIGHT 45.0f

#define CHECK_POINT_TEXTURE_POSITION_X WINDOW_WIDTH - 2*CHECK_POINT_TEXTURE_WIDTH
#define CHECK_POINT_TEXTURE_POSITION_Y WINDOW_HEIGHT/6
#define CHECK_POINT_TEXTURE_LABEL_SPACE 60.0f
//**********CHECK POINT SETTING*******************//

//**********BACKGROUND SETTING********************//
#define HERO_BACKGROUND_POSITION_X WINDOW_WIDTH/6
#define HERO_BACKGROUND_POSITION_Y WINDOW_HEIGHT/6
//**********BACKGROUND SETTING********************//










// system display setting
#define WINDOW_WIDTH 							800
#define WINDOW_HEIGHT 							450
#define FPS           							60
#define MAXIMUM_LEVEL                           3



// useless????
#define BOUNDING_BOX_INITIAL_X 64.0f
#define BOUNDING_BOX_INITIAL_Y 32.0f
#define BOUNDARY_INITIAL_WIDTH 1280
#define BOUNDARY_INITIAL_HEIGHT 720
#define WALL_INITIAL_WIDTH 					1290.0f
#define WALL_INITIAL_HEIGHT 				5.0f
#define WALL_BOUNDING_BOX_X 				1290.0f
#define WALL_BOUNDING_BOX_Y 				5.0f
#define WALL_TOP_INITIAL_POS_X 640.0f
#define WALL_TOP_INITIAL_POS_Y -5.0f
#define WALL_TOP_INITIAL_WIDTH 1300.0f
#define WALL_TOP_INITIAL_HEIGHT 10.0f
#define WALL_TOP_NORMAL_X 0.0f
#define WALL_TOP_NORMAL_Y 1.0f
#define WALL_LEFT_INITIAL_POS_X -5.0f
#define WALL_LEFT_INITIAL_POS_Y 360.0f
#define WALL_LEFT_INITIAL_WIDTH 10.0f
#define WALL_LEFT_INITIAL_HEIGHT 1300.0f
#define WALL_LEFT_NORMAL_X 1.0f
#define WALL_LEFT_NORMAL_Y 0.0f
#define WALL_RIGHT_INITIAL_POS_X 1285.0f
#define WALL_RIGHT_INITIAL_POS_Y 360.0f
#define WALL_RIGHT_INITIAL_WIDTH 10.0f
#define WALL_RIGHT_INITIAL_HEIGHT 1300.0f
#define WALL_RIGHT_NORMAL_X -1.0f
#define WALL_RIGHT_NORMAL_Y 0.0f
#define WALL_MASS 30.0f
#define SETTING_MENU_RETURN_BUTTON_TEXT_TEXTURE_POSITION_X 640.0f
#define SETTING_MENU_RETURN_BUTTON_TEXT_TEXTURE_POSITION_Y 340.0f




// #define IS_ALIVE true
// #define IS_DEAD false
// #define HERO_RADIUS 10.0f
// #define HERO_INITIAL_POSITION_X 640.0f
// #define HERO_INITIAL_POSITION_Y 640.0f
// #define HERO_INITIAL_VELOCITY_X 10.0f
// #define HERO_INITIAL_VELOCITY_Y -12.0f
// #define HERO_VELOCITY_FACTOR sqrt(224.0f)
// #define HERO_BOUNDING_BOX_X 10.0f
// #define HERO_BOUNDING_BOX_Y 10.0f
// #define MINION_INITIAL_WIDTH 64.0f
// #define MINION_INITIAL_HEIGHT 32.0f
// #define MINION_BOUNDING_BOX_X 64.0f
// #define MINION_BOUNDING_BOX_Y 32.0f
// #define COLLIDER_INITIAL_MASS 10.0f
// #define COLLIDER_INITIAL_ELASTIC 1.0f
// #define COLLIDER_INITIAL_POSITION_X 100.0f
// #define COLLIDER_INITIAL_POSITION_Y 100.0f
// #define COLLIDER_INITIAL_VELOCITY_X 0.0f
// #define COLLIDER_INITIAL_VELOCITY_Y 0.0f
// #define COLLIDER_INITIAL_ACCELERATION_X 0.0f
// #define COLLIDER_INITIAL_ACCELERATION_Y 0.0f
// #define BOUNDING_BOX_INITIAL_X 64.0f
// #define BOUNDING_BOX_INITIAL_Y 32.0f
// #define BOUNDARY_INITIAL_WIDTH 1280
// #define BOUNDARY_INITIAL_HEIGHT 720
// #define WALL_INITIAL_WIDTH 1290.0f
// #define WALL_INITIAL_HEIGHT 5.0f
// #define WALL_BOUNDING_BOX_X 1290.0f
// #define WALL_BOUNDING_BOX_Y 5.0f
// #define NORMAL_INITIAL_X 0.0f
// #define NORMAL_INITIAL_Y -1.0f
// #define SCREEN_WIDTH 1280
// #define SCREEN_HEIGHT 720
// #define PADDLE_INITIAL_POS_X 640.0f
// #define PADDLE_INITIAL_POS_Y 680.0f
// #define PADDLE_INITIAL_SIZE_X 104.0f
// #define PADDLE_INITIAL_SIZE_Y 24.0f
// #define PADDLE_VELOCITY_FACTOR 20.0f
// #define PADDLE_BOUNDING_BOX_X 104.0f
// #define PADDLE_BOUNDING_BOX_Y 24.0f
// #define MINION_LEVEL_ONE_NUM 48
// #define MINION_LEVEL_TWO_NUM 48
// #define MINION_LEVEL_THREE_NUM 48
// #define QUIT true
// #define WINDOW_WIDTH 1280
// #define WINDOW_HEIGHT 720
// #define LIFE_TEXTURE_POSITION_X 100.0f
// #define LIFE_TEXTURE_POSITION_Y 30.0f
// #define SCORE_TEXTURE_POSITION_X 1000.0f
// #define SCORE_TEXTURE_POSITION_Y 30.0f
// #define LEVEL_TEXTURE_POSITION_X 500.0f
// #define LEVEL_TEXTURE_POSITION_Y 30.0f
// #define LOSE_TEXTURE_POSITION_X 640.0f
// #define LOSE_TEXTURE_POSITION_Y 360.0f
// #define WIN_TEXTURE_POSITION_X 640.0f
// #define WIN_TEXTURE_POSITION_Y 360.0f
// #define WALL_TOP_INITIAL_POS_X 640.0f
// #define WALL_TOP_INITIAL_POS_Y -5.0f
// #define WALL_TOP_INITIAL_WIDTH 1300.0f
// #define WALL_TOP_INITIAL_HEIGHT 10.0f
// #define WALL_TOP_NORMAL_X 0.0f
// #define WALL_TOP_NORMAL_Y 1.0f
// #define WALL_LEFT_INITIAL_POS_X -5.0f
// #define WALL_LEFT_INITIAL_POS_Y 360.0f
// #define WALL_LEFT_INITIAL_WIDTH 10.0f
// #define WALL_LEFT_INITIAL_HEIGHT 1300.0f
// #define WALL_LEFT_NORMAL_X 1.0f
// #define WALL_LEFT_NORMAL_Y 0.0f
// #define WALL_RIGHT_INITIAL_POS_X 1285.0f
// #define WALL_RIGHT_INITIAL_POS_Y 360.0f
// #define WALL_RIGHT_INITIAL_WIDTH 10.0f
// #define WALL_RIGHT_INITIAL_HEIGHT 1300.0f
// #define WALL_RIGHT_NORMAL_X -1.0f
// #define WALL_RIGHT_NORMAL_Y 0.0f
// #define HERO_MASS 5.0f
// #define WALL_MASS 30.0f
// #define PADDLE_MASS 10.0f
// #define MINION_MASS 15.0F
// #define PADDLE_ELASTIC 0.5f
// #define MAIN_MENU_TEXTURE_POSITION_X 640.0f
// #define MAIN_MENU_TEXTURE_POSITION_Y 100.0f
// #define START_TEXT_TEXTURE_POSITION_X 640.f
// #define START_TEXT_TEXTURE_POSITION_Y 180.0f
// #define MAIN_MENU_START_BUTTON_POSITION_X 540.0f
// #define MAIN_MENU_START_BUTTON_POSITION_Y 155.0f
// #define LANGUAGE_SETTING_TEXT_TEXTURE_POSITION_X 640.0f
// #define LANGUAGE_SETTING_TEXT_TEXTURE_POSITION_Y 260.0f
// #define MAIN_MENU_LANGUAGE_SETTING_BUTTON_POSITION_X 540.0f
// #define MAIN_MENU_LANGUAGE_SETTING_BUTTON_POSITION_Y 235.0f
// #define QUIT_TEXT_TEXTURE_POSITION_X 640.0f
// #define QUIT_TEXT_TEXTURE_POSITION_Y 340.0f
// #define PAUSE_TEXT_TEXTURE_POSITION_X 640.0f
// #define PAUSE_TEXT_TEXTURE_POSITION_Y 420.0f
// #define RETURN_TEXT_TEXTURE_POSITION_X 640.0f
// #define RETURN_TEXT_TEXTURE_POSITION_Y 500.0f
// #define PAUSE_MENU_TEXTURE_POSITION_X 640.0f
// #define PAUSE_MENU_TEXTURE_POSITION_Y 300.0f
// #define RESUME_TEXT_TEXTURE_POSITION_X 640.0f
// #define RESUME_TEXT_TEXTURE_POSITION_Y 380.0f
// #define SETTING_MENU_TEXTURE_POSITION_X 640.0f
// #define SETTING_MENU_TEXTURE_POSITION_Y 100.0f
// #define FIRST_LANGUAGE_TEXT_TEXTURE_POSITION_X 640.0f
// #define FIRST_LANGUAGE_TEXT_TEXTURE_POSITION_Y 180.0f
// #define SETTING_MENU_FIRST_LANGUAGE_BUTTON_POSITION_X 540.0f
// #define SETTING_MENU_FIRST_LANGUAGE_BUTTON_POSITION_Y 155.0f
// #define SECOND_LANGUAGE_TEXT_TEXTURE_POSITION_X 640.0f
// #define SECOND_LANGUAGE_TEXT_TEXTURE_POSITION_Y 260.0f
// #define SETTING_MENU_SECOND_LANGUAGE_BUTTON_POSITION_X 540.0f
// #define SETTING_MENU_SECOND_LANGUAGE_BUTTON_POSITION_Y 235.0f
// #define SETTING_MENU_RETURN_BUTTON_TEXT_TEXTURE_POSITION_X 640.0f
// #define SETTING_MENU_RETURN_BUTTON_TEXT_TEXTURE_POSITION_Y 340.0f
// #define RETURN_BUTTON_POSITION_X 540.0f
// #define RETURN_BUTTON_POSITION_Y 310.0f




// #define BUTTON_WIDTH 190.0f
// #define BUTTON_HEIGHT 49.0f
// #define BUTTON_SIZE_X 190.0f
// #define BUTTON_SIZE_Y 49.0f












#endif /* Constants_h */
