#ifndef Constants_h
#define Constants_h


#define QUIT true


/* GAME OBJECTS CONSTANTS */

// global game objects
#define GRAVITY 							50.0f
#define MAX_VELOCITY_X 						30.0f
#define MAX_VELOCITY_Y 						50.0f
#define IS_ALIVE 							true
#define IS_DEAD 							false
#define COLLIDER_INITIAL_ACCELERATION_X 	0.0f
#define COLLIDER_INITIAL_ACCELERATION_Y 	0.0f
#define COLLIDER_INITIAL_MASS 				10.0f
#define COLLIDER_INITIAL_ELASTIC 			1.0f
#define COLLIDER_INITIAL_POSITION_X 		0.0f
#define COLLIDER_INITIAL_POSITION_Y 		0.0f
#define COLLIDER_INITIAL_VELOCITY_X 		0.0f
#define COLLIDER_INITIAL_VELOCITY_Y 		0.0f
//#define MAP_WIDTH                            2000
//#define MAP_HEIGHT                            2000

// Collisions
#define COLLISION_TYPE_NONE					0

#define COLLISION_TYPE_HERO_MINION			1
#define COLLISION_TYPE_HERO_BASIC		    2
#define COLLISION_TYPE_HERO_SURFACE         3
#define COLLISION_TYPE_HERO_WATER           4
#define COLLISION_TYPE_HERO_ICE             5
#define COLLISION_TYPE_HERO_POWERUP			11

#define COLLISION_TYPE_MINION_MINION		13
#define COLLISION_TYPE_MINION_BASIC		    7
#define COLLISION_TYPE_MINION_SURFACE       8
#define COLLISION_TYPE_MINION_WATER         9
#define COLLISION_TYPE_MINION_ICE           10

#define COLLISION_TYPE_POWERUP_SURFACE		12
#define COLLISION_TYPE_POWERUP_ICE          14
#define COLLISION_TYPE_POWERUP_WATER		15
#define COLLISION_TYPE_POWERUP_BASIC        16

#define COLLISION_TYPE_BULLET_HERO         	17
#define COLLISION_TYPE_BULLET_SURFACE       18
#define COLLISION_TYPE_BULLET_ICE			19
#define COLLISION_TYPE_BULLET_WATER			20
#define COLLISION_TYPE_BULLET_MINION		21

// hero initial
#define HERO_INITIAL_POSITION_X 		    76.0f
#define HERO_INITIAL_POSITION_Y 			600.0f
#define HERO_INITIAL_VELOCITY_X 			5.0f
#define HERO_INITIAL_VELOCITY_Y 			0.0f
#define HERO_JUMP_UP_SPEED 					10.0f
#define HERO_WIDTH_INITIAL					100.0f
#define HERO_HEIGHT_INITIAL					100.0f
#define HERO_BOUNDING_BOX_X 				100.0f
#define HERO_BOUNDING_BOX_Y 				100.0f
#define HERO_MASS 							5.0f
#define HERO_ANIMATION_MAX_FRAME_NUM 		8
#define HERO_FRAME_HEIGHT 					128
#define HERO_FRAME_WIDTH 					128

#define HERO_POSE_COUNT						9

#define HERO_POSE_FIRE						8
#define HERO_POSE_FALL_RIGHT				7
#define HERO_POSE_FALL_LEFT					6
#define HERO_POSE_JUMP_LEFT					5
#define HERO_POSE_JUMP_RIGHT				4
#define HERO_POSE_MOVE_LEFT					3
#define HERO_POSE_MOVE_RIGHT				2
#define HERO_POSE_STAND_LEFT				1
#define HERO_POSE_STAND_RIGHT				0

#define HERO_COLLISION_INVALID_TIME			3000

#define HERO_POS_MOVE_FACTOR				0.05	



// minion initial
#define MINION_INITIAL_WIDTH 				100.0f
#define MINION_INITIAL_HEIGHT 				100.0f
#define MINION_INITIAL_VELOCITY_X 			5.0f
#define MINION_INITIAL_VELOCITY_Y 			0.0f
#define MINION_BOUNDING_BOX_X 				100.0f
#define MINION_BOUNDING_BOX_Y 				100.0f
#define MINION_MASS 						15.0f
#define MINION_LEVEL_ONE_NUM 				48
#define MINION_LEVEL_TWO_NUM 				48
#define MINION_LEVEL_THREE_NUM 				48
#define MINION_FRAME_WIDTH					60
#define MINION_FRAME_HEIGHT					60
#define MINION_ANIMATION_MAX_FRAME_NUM		6
#define MINION_POSE_COUNT					10
#define MINION_POSE_MOVE_RIGHT				0
#define MINION_POSE_MOVE_LEFT				1
#define MINION_POSE_JUMP_LEFT				2
#define MINION_POSE_JUMP_RIGHT				3
#define MINION_POSE_CRUNCH_LEFT				4
#define MINION_POSE_CRUNCH_RIGHT			5
#define MINION_POSE_STAND_LEFT				6
#define MINION_POSE_STAND_RIGHT				7
#define MINION_POSE_FALL_LEFT				8
#define MINION_POSE_FALL_RIGHT				9

#define MINION_COLLISION_STOP_TIME			3000
#define MINION_POS_MOVE_FACTOR				0.1	

// powerup initial
#define POWERUP_INITIAL_WIDTH				100.0f
#define POWERUP_INITIAL_HEIGHT				100.0f
#define POWERUP_BOUNDING_BOX_X 				100.0f
#define POWERUP_BOUNDING_BOX_Y 				100.0f
#define POWERUP_MASS 						15.0F
#define POWERUP_CODE_COUNT					3
#define POWERUP_CODE_NONE					0
#define POWERUP_CODE_ONE_MORE_LIFE			1
#define POWERUP_CODE_SPEED_UP				2
#define POWERUP_SPEED_UP_MAX_SPEED          50.0f
#define POWERUP_CODE_FLOAT					3
#define POWERUP_FLOAT_GRAVITY		        30.0f
#define POWERUP_CODE_FIRE					4
#define POWERUP_ANIMATION_MAX_FRAME_NUM		5
#define POWERUP_FRAME_WIDTH					30
#define POWERUP_FRAME_HEIGHT				25
#define POWERUP_POSE_BLING					1
#define POWERUP_POSE_DIM					2

// bullet initial
#define BULLET_INITIAL_WIDTH				40.0f
#define BULLET_INITIAL_HEIGHT				40.0f
#define BULLET_INITIAL_VELOCITY_X			5.0f
#define BULLET_INITIAL_VELOCITY_Y			0.0f
#define BULLET_MASS							15.0f
#define BULLET_BOUNDING_BOX_X				40.0f
#define BULLET_BOUNDING_BOX_Y				40.0f
#define BULLET_FRAME_WIDTH					13
#define BULLET_FRAME_HEIGHT					13
#define BULLET_ANIMATION_MAX_FRAME_NUM		6
#define BULLET_POSE_COUNT					2
#define BULLET_POSE_FLY_LEFT				0
#define BULLET_POSE_FLY_RIGHT				1

// tile initial
#define TILE_INITIAL_WIDTH					151.0f
#define TILE_INITIAL_HEIGHT					100.0f
#define TILE_TYPE_BASIC						1
#define TILE_TYPE_SURFACE					2
#define TILE_TYPE_WATER						3
#define TILE_TYPE_ICE						4

// map initial
#define MAP_TYPE_NONE                       1
#define MAP_TYPE_NORMAL                     2
#define MAP_TYPE_SEA                        3
#define MAP_TYPE_SNOW                       4
#define MAP_WIDTH                           1510.0
#define MAP_HEIGHT                          800.0F

// camera initial
#define CAMERA_MODE_CENTER					1
#define CAMERA_MODE_TOP_LEFT				2
#define CAMERA_OFFSET_FROM_HERO_X			10
#define CAMERA_OFFSET_FROM_HERO_Y			10



// game info initial
#define LIFE_TEXTURE_POSITION_X 			100.0F
#define LIFE_TEXTURE_POSITION_Y 			30.0f
#define SCORE_TEXTURE_POSITION_X 			1000.0f
#define SCORE_TEXTURE_POSITION_Y 			30.0f
#define LEVEL_TEXTURE_POSITION_X 			500.0f
#define LEVEL_TEXTURE_POSITION_Y 			30.0f
#define LOSE_TEXTURE_POSITION_X 			640.0f
#define LOSE_TEXTURE_POSITION_Y 			360.0f
#define WIN_TEXTURE_POSITION_X 				640.0f
#define WIN_TEXTURE_POSITION_Y 				360.0f
#define INIT_LEVEL 							1
#define INIT_LIFE 							3






/* GAME SETTING CONSTANTS*/

// language setting
#define CURRENT_LANGUAGE 1
#define LANGUAGE_ENGLISH 1
#define LANGUAGE_CHINESE 2

// menu setting
#define LANGUAGE_SETTING_TEXT_TEXTURE_POSITION_X 640.0f
#define LANGUAGE_SETTING_TEXT_TEXTURE_POSITION_Y 260.0f
#define FIRST_LANGUAGE_TEXT_TEXTURE_POSITION_X 640.0f
#define FIRST_LANGUAGE_TEXT_TEXTURE_POSITION_Y 180.0f
#define SETTING_MENU_FIRST_LANGUAGE_BUTTON_POSITION_X 540.0f
#define SETTING_MENU_FIRST_LANGUAGE_BUTTON_POSITION_Y 155.0f
#define SECOND_LANGUAGE_TEXT_TEXTURE_POSITION_X 640.0f
#define SECOND_LANGUAGE_TEXT_TEXTURE_POSITION_Y 260.0f
#define SETTING_MENU_SECOND_LANGUAGE_BUTTON_POSITION_X 540.0f
#define SETTING_MENU_SECOND_LANGUAGE_BUTTON_POSITION_Y 235.0f
#define MAIN_MENU_LANGUAGE_SETTING_BUTTON_POSITION_X 540.0f
#define MAIN_MENU_LANGUAGE_SETTING_BUTTON_POSITION_Y 235.0f
#define RETURN_BUTTON_POSITION_X 540.0f
#define RETURN_BUTTON_POSITION_Y 310.0f
#define MAIN_MENU_TEXTURE_POSITION_X 640.0f
#define MAIN_MENU_TEXTURE_POSITION_Y 100.0f
#define START_TEXT_TEXTURE_POSITION_X 640.f
#define START_TEXT_TEXTURE_POSITION_Y 180.0f
#define MAIN_MENU_START_BUTTON_POSITION_X 540.0f
#define MAIN_MENU_START_BUTTON_POSITION_Y 155.0f
#define QUIT_TEXT_TEXTURE_POSITION_X 640.0f
#define QUIT_TEXT_TEXTURE_POSITION_Y 340.0f
#define PAUSE_TEXT_TEXTURE_POSITION_X 640.0f
#define PAUSE_TEXT_TEXTURE_POSITION_Y 420.0f
#define RETURN_TEXT_TEXTURE_POSITION_X 640.0f
#define RETURN_TEXT_TEXTURE_POSITION_Y 500.0f
#define PAUSE_MENU_TEXTURE_POSITION_X 640.0f
#define PAUSE_MENU_TEXTURE_POSITION_Y 300.0f
#define RESUME_TEXT_TEXTURE_POSITION_X 640.0f
#define RESUME_TEXT_TEXTURE_POSITION_Y 380.0f
#define SETTING_MENU_TEXTURE_POSITION_X 640.0f
#define SETTING_MENU_TEXTURE_POSITION_Y 100.0f
#define BUTTON_WIDTH 190.0f
#define BUTTON_HEIGHT 49.0f
#define BUTTON_SIZE_X 190.0f
#define BUTTON_SIZE_Y 49.0f
#define MAIN_MENU_LABEL_SPACE 80.0f
#define MAIN_MENU_QUIT_BUTTON_POSITION_X 540.0f
#define MAIN_MENU_QUIT_BUTTON_POSITION_Y 395.0f
#define MAIN_MENU_INSTRUCTION_BUTTON_POSITION_X 540.0f
#define MAIN_MENU_INSTRUCTION_BUTTON_POSITION_Y 315.0f

#define SETTING_MENU_LABEL_SPACE 80.0f
#define SETTING_MENU_RETURN_BUTTON_POSITION_X 540.0f
#define SETTING_MENU_RETURN_BUTTON_POSITION_Y 315.0f

#define INSTRUCTION_MENU_TEXTURE_POSITION_X 640.0f
#define INSTRUCTION_MENU_TEXTURE_POSITION_Y 100.0f
#define INSTRUCTION_MENU_LABEL_SPACE 80.0f
#define INSTRUCTION_MENU_RETURN_BUTTON_POSITION_X 540.0f
#define INSTRUCTION_MENU_RETURN_BUTTON_POSITION_Y 475.0f

#define PAUSE_MENU_LABEL_SPACE 80.0f

#define PASS_MENU_TEXTURE_POSITION_X 640.0f
#define PASS_MENU_TEXTURE_POSITION_Y 100.0f
#define PASS_MENU_LABEL_SPACE 80.0f

#define PASS_MENU_NEXT_BUTTON_POSITION_X 540.0f
#define PASS_MENU_NEXT_BUTTON_POSITION_Y 180.0f


// system display setting
#define WINDOW_WIDTH 							1510
#define WINDOW_HEIGHT 							800
#define FPS           							60
#define MAXIMUM_LEVEL                           3



// useless????
#define BOUNDING_BOX_INITIAL_X 64.0f
#define BOUNDING_BOX_INITIAL_Y 32.0f
#define BOUNDARY_INITIAL_WIDTH 1280
#define BOUNDARY_INITIAL_HEIGHT 720
#define WALL_INITIAL_WIDTH 					1290.0f
#define WALL_INITIAL_HEIGHT 				5.0f
#define WALL_BOUNDING_BOX_X 				1290.0f
#define WALL_BOUNDING_BOX_Y 				5.0f
#define WALL_TOP_INITIAL_POS_X 640.0f
#define WALL_TOP_INITIAL_POS_Y -5.0f
#define WALL_TOP_INITIAL_WIDTH 1300.0f
#define WALL_TOP_INITIAL_HEIGHT 10.0f
#define WALL_TOP_NORMAL_X 0.0f
#define WALL_TOP_NORMAL_Y 1.0f
#define WALL_LEFT_INITIAL_POS_X -5.0f
#define WALL_LEFT_INITIAL_POS_Y 360.0f
#define WALL_LEFT_INITIAL_WIDTH 10.0f
#define WALL_LEFT_INITIAL_HEIGHT 1300.0f
#define WALL_LEFT_NORMAL_X 1.0f
#define WALL_LEFT_NORMAL_Y 0.0f
#define WALL_RIGHT_INITIAL_POS_X 1285.0f
#define WALL_RIGHT_INITIAL_POS_Y 360.0f
#define WALL_RIGHT_INITIAL_WIDTH 10.0f
#define WALL_RIGHT_INITIAL_HEIGHT 1300.0f
#define WALL_RIGHT_NORMAL_X -1.0f
#define WALL_RIGHT_NORMAL_Y 0.0f
#define WALL_MASS 30.0f
#define SETTING_MENU_RETURN_BUTTON_TEXT_TEXTURE_POSITION_X 640.0f
#define SETTING_MENU_RETURN_BUTTON_TEXT_TEXTURE_POSITION_Y 340.0f




// #define IS_ALIVE true
// #define IS_DEAD false
// #define HERO_RADIUS 10.0f
// #define HERO_INITIAL_POSITION_X 640.0f
// #define HERO_INITIAL_POSITION_Y 640.0f
// #define HERO_INITIAL_VELOCITY_X 10.0f
// #define HERO_INITIAL_VELOCITY_Y -12.0f
// #define HERO_VELOCITY_FACTOR sqrt(224.0f)
// #define HERO_BOUNDING_BOX_X 10.0f
// #define HERO_BOUNDING_BOX_Y 10.0f
// #define MINION_INITIAL_WIDTH 64.0f
// #define MINION_INITIAL_HEIGHT 32.0f
// #define MINION_BOUNDING_BOX_X 64.0f
// #define MINION_BOUNDING_BOX_Y 32.0f
// #define COLLIDER_INITIAL_MASS 10.0f
// #define COLLIDER_INITIAL_ELASTIC 1.0f
// #define COLLIDER_INITIAL_POSITION_X 100.0f
// #define COLLIDER_INITIAL_POSITION_Y 100.0f
// #define COLLIDER_INITIAL_VELOCITY_X 0.0f
// #define COLLIDER_INITIAL_VELOCITY_Y 0.0f
// #define COLLIDER_INITIAL_ACCELERATION_X 0.0f
// #define COLLIDER_INITIAL_ACCELERATION_Y 0.0f
// #define BOUNDING_BOX_INITIAL_X 64.0f
// #define BOUNDING_BOX_INITIAL_Y 32.0f
// #define BOUNDARY_INITIAL_WIDTH 1280
// #define BOUNDARY_INITIAL_HEIGHT 720
// #define WALL_INITIAL_WIDTH 1290.0f
// #define WALL_INITIAL_HEIGHT 5.0f
// #define WALL_BOUNDING_BOX_X 1290.0f
// #define WALL_BOUNDING_BOX_Y 5.0f
// #define NORMAL_INITIAL_X 0.0f
// #define NORMAL_INITIAL_Y -1.0f
// #define SCREEN_WIDTH 1280
// #define SCREEN_HEIGHT 720
// #define PADDLE_INITIAL_POS_X 640.0f
// #define PADDLE_INITIAL_POS_Y 680.0f
// #define PADDLE_INITIAL_SIZE_X 104.0f
// #define PADDLE_INITIAL_SIZE_Y 24.0f
// #define PADDLE_VELOCITY_FACTOR 20.0f
// #define PADDLE_BOUNDING_BOX_X 104.0f
// #define PADDLE_BOUNDING_BOX_Y 24.0f
// #define MINION_LEVEL_ONE_NUM 48
// #define MINION_LEVEL_TWO_NUM 48
// #define MINION_LEVEL_THREE_NUM 48
// #define QUIT true
// #define WINDOW_WIDTH 1280
// #define WINDOW_HEIGHT 720
// #define LIFE_TEXTURE_POSITION_X 100.0f
// #define LIFE_TEXTURE_POSITION_Y 30.0f
// #define SCORE_TEXTURE_POSITION_X 1000.0f
// #define SCORE_TEXTURE_POSITION_Y 30.0f
// #define LEVEL_TEXTURE_POSITION_X 500.0f
// #define LEVEL_TEXTURE_POSITION_Y 30.0f
// #define LOSE_TEXTURE_POSITION_X 640.0f
// #define LOSE_TEXTURE_POSITION_Y 360.0f
// #define WIN_TEXTURE_POSITION_X 640.0f
// #define WIN_TEXTURE_POSITION_Y 360.0f
// #define WALL_TOP_INITIAL_POS_X 640.0f
// #define WALL_TOP_INITIAL_POS_Y -5.0f
// #define WALL_TOP_INITIAL_WIDTH 1300.0f
// #define WALL_TOP_INITIAL_HEIGHT 10.0f
// #define WALL_TOP_NORMAL_X 0.0f
// #define WALL_TOP_NORMAL_Y 1.0f
// #define WALL_LEFT_INITIAL_POS_X -5.0f
// #define WALL_LEFT_INITIAL_POS_Y 360.0f
// #define WALL_LEFT_INITIAL_WIDTH 10.0f
// #define WALL_LEFT_INITIAL_HEIGHT 1300.0f
// #define WALL_LEFT_NORMAL_X 1.0f
// #define WALL_LEFT_NORMAL_Y 0.0f
// #define WALL_RIGHT_INITIAL_POS_X 1285.0f
// #define WALL_RIGHT_INITIAL_POS_Y 360.0f
// #define WALL_RIGHT_INITIAL_WIDTH 10.0f
// #define WALL_RIGHT_INITIAL_HEIGHT 1300.0f
// #define WALL_RIGHT_NORMAL_X -1.0f
// #define WALL_RIGHT_NORMAL_Y 0.0f
// #define HERO_MASS 5.0f
// #define WALL_MASS 30.0f
// #define PADDLE_MASS 10.0f
// #define MINION_MASS 15.0F
// #define PADDLE_ELASTIC 0.5f
// #define MAIN_MENU_TEXTURE_POSITION_X 640.0f
// #define MAIN_MENU_TEXTURE_POSITION_Y 100.0f
// #define START_TEXT_TEXTURE_POSITION_X 640.f
// #define START_TEXT_TEXTURE_POSITION_Y 180.0f
// #define MAIN_MENU_START_BUTTON_POSITION_X 540.0f
// #define MAIN_MENU_START_BUTTON_POSITION_Y 155.0f
// #define LANGUAGE_SETTING_TEXT_TEXTURE_POSITION_X 640.0f
// #define LANGUAGE_SETTING_TEXT_TEXTURE_POSITION_Y 260.0f
// #define MAIN_MENU_LANGUAGE_SETTING_BUTTON_POSITION_X 540.0f
// #define MAIN_MENU_LANGUAGE_SETTING_BUTTON_POSITION_Y 235.0f
// #define QUIT_TEXT_TEXTURE_POSITION_X 640.0f
// #define QUIT_TEXT_TEXTURE_POSITION_Y 340.0f
// #define PAUSE_TEXT_TEXTURE_POSITION_X 640.0f
// #define PAUSE_TEXT_TEXTURE_POSITION_Y 420.0f
// #define RETURN_TEXT_TEXTURE_POSITION_X 640.0f
// #define RETURN_TEXT_TEXTURE_POSITION_Y 500.0f
// #define PAUSE_MENU_TEXTURE_POSITION_X 640.0f
// #define PAUSE_MENU_TEXTURE_POSITION_Y 300.0f
// #define RESUME_TEXT_TEXTURE_POSITION_X 640.0f
// #define RESUME_TEXT_TEXTURE_POSITION_Y 380.0f
// #define SETTING_MENU_TEXTURE_POSITION_X 640.0f
// #define SETTING_MENU_TEXTURE_POSITION_Y 100.0f
// #define FIRST_LANGUAGE_TEXT_TEXTURE_POSITION_X 640.0f
// #define FIRST_LANGUAGE_TEXT_TEXTURE_POSITION_Y 180.0f
// #define SETTING_MENU_FIRST_LANGUAGE_BUTTON_POSITION_X 540.0f
// #define SETTING_MENU_FIRST_LANGUAGE_BUTTON_POSITION_Y 155.0f
// #define SECOND_LANGUAGE_TEXT_TEXTURE_POSITION_X 640.0f
// #define SECOND_LANGUAGE_TEXT_TEXTURE_POSITION_Y 260.0f
// #define SETTING_MENU_SECOND_LANGUAGE_BUTTON_POSITION_X 540.0f
// #define SETTING_MENU_SECOND_LANGUAGE_BUTTON_POSITION_Y 235.0f
// #define SETTING_MENU_RETURN_BUTTON_TEXT_TEXTURE_POSITION_X 640.0f
// #define SETTING_MENU_RETURN_BUTTON_TEXT_TEXTURE_POSITION_Y 340.0f
// #define RETURN_BUTTON_POSITION_X 540.0f
// #define RETURN_BUTTON_POSITION_Y 310.0f




// #define BUTTON_WIDTH 190.0f
// #define BUTTON_HEIGHT 49.0f
// #define BUTTON_SIZE_X 190.0f
// #define BUTTON_SIZE_Y 49.0f












#endif /* Constants_h */
